name: Release

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0
      - name: "Setup Java"
        uses: "actions/setup-java@v1"
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: "Cache Gradle wrapper"
        uses: "actions/cache@v2"
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/notifications
          key: "gradle-wrapper-${{ runner.os }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}"
      - name: "Cache Gradle dependencies"
        uses: "actions/cache@v2"
        with:
          path: "~/.gradle/caches"
          key: "gradle-caches-${{ runner.os }}-${{ hashFiles('**/gradle/dependency-locks/*.lockfile') }}"
      - name: "Gradle publish"
        env:
          GRADLE_OPTS: "-Dorg.gradle.project.gradle.publish.key=${{ secrets.GRADLE_PLUGIN_KEY }} -Dorg.gradle.project.gradle.publish.secret=${{ secrets.GRADLE_PLUGIN_SECRET }}"
        run: "./gradlew publishPlugins"
      - name: "Github package publish"
        env:
          GRADLE_OPTS: "-Dorg.gradle.project.gradle.publish.key=${{ secrets.GRADLE_PLUGIN_KEY }} -Dorg.gradle.project.gradle.publish.secret=${{ secrets.GRADLE_PLUGIN_SECRET }}"
        run: "./gradlew publishPlugins"
      - name: "Github packages publish"
        env:
          packageUser: ${{ secrets.USERNAME }}
          packagePAT: ${{ secrets.TOKEN }}
        run: "./gradlew publish"
